import asyncio
import math
import os
import re
import subprocess
import tempfile
from typing import Any, Dict, List, Tuple, Optional, Callable
from faster_whisper import WhisperModel
from config import get_settings

# Try import fastText (optional). If unavailable, LID is disabled.
try:
    import fasttext  # type: ignore
except Exception:
    fasttext = None

_SUPPORTED = {"int8", "float32"}

def _sanitize_compute_type(ct: str) -> str:
    return ct if ct in _SUPPORTED else "int8"

def _safe_progress(cb: Callable[[float], None], value: float) -> None:
    try:
        cb(value)
    except Exception:
        pass

def _fmt_pct(x: float) -> str:
    try:
        return f"{x*100:.1f}%"
    except Exception:
        return "?"

# ---------------- ffmpeg helpers ----------------

def _ffprobe_duration_sec(path: str) -> float:
    try:
        cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration",
               "-of", "default=noprint_wrappers=1:nokey=1", path]
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, timeout=10)
        s = (out.decode("utf-8", "ignore").strip() or "0")
        return max(0.0, float(s))
    except Exception:
        return 0.0

def _ffmpeg_extract_wav_chunk(src: str, start: float, dur: float, out_path: str, lookbehind: float = 0.0) -> Tuple[bool, float]:
    try:
        real_start = max(0.0, start - max(0.0, lookbehind))
        t = max(0.01, dur + (start - real_start))
        cmd = [
            "ffmpeg", "-y",
            "-ss", f"{real_start:.3f}",
            "-t", f"{t:.3f}",
            "-i", src,
            "-vn",
            "-ac", "1",
            "-ar", "16000",
            "-f", "wav",
            out_path,
        ]
        subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=max(10, int(t*5)))
        return (os.path.exists(out_path) and os.path.getsize(out_path) > 0, real_start)
    except Exception:
        return (False, start)

# ---------------- Text heuristics ----------------

_ACCENT_FR = set("àâäæçéèêëîïôœùûüÿ’")
_CJK_BLOCK = lambda ch: ord(ch) >= 0x2E80

def _looks_like_disclaimer(text: str) -> bool:
    t = (text or "").strip()
    if not t or len(t) > 120:
        return False
    lower = t.lower()
    patterns = [
        r"^transcribed by\b",
        r"^auto(\-|\s)?generated\b",
        r"^generated by\b",
        r"^captions by\b",
        r"^subtitles by\b",
        r"^.*(auto[-\s]?transcription).*",
    ]
    return any(re.search(p, lower) for p in patterns)

def _analyze_chars(text: str) -> Dict[str, Any]:
    accents = sum(1 for c in text if c in _ACCENT_FR)
    latin = sum(1 for c in text if 'a' <= c.lower() <= 'z')
    cjk = sum(1 for c in text if _CJK_BLOCK(c))
    total = len(text)
    return {
        "accents": accents,
        "latin": latin,
        "cjk": cjk,
        "total": total,
        "accent_ratio": (accents / total) if total else 0.0,
        "cjk_ratio": (cjk / total) if total else 0.0,
        "latin_ratio": (latin / total) if total else 0.0,
    }

def _should_correct_lang(lang: str, prev_lang: str, text: str) -> Optional[str]:
    stats = _analyze_chars(text)
    if lang in ("zh", "ja", "ko") and stats["cjk"] == 0 and stats["latin_ratio"] > 0.6:
        return prev_lang if prev_lang not in ("unknown", "") else "en"
    if lang == "es" and stats["accent_ratio"] > 0.03 and stats["accents"] >= 5:
        return "fr"
    if lang == "en" and stats["accent_ratio"] > 0.03 and stats["accents"] >= 5:
        return "fr" if prev_lang in ("fr", "en", "unknown") else prev_lang
    return None

def _is_noise_segment(text: str) -> bool:
    t = (text or "").strip()
    if not t:
        return True
    if len(t) >= 3 and all(ch in "_-." for ch in t):
        return True
    non_word = sum(1 for c in t if not c.isalnum())
    if non_word / len(t) > 0.8 and len(t) <= 25:
        return True
    return False

# ---------------- Splitting ----------------

def _split_segment_by_words(seg: Dict[str, Any], max_len_sec: float, words: List[Dict[str, Any]],
                            max_chars: int, subseg_max_sec: float) -> List[Dict[str, Any]]:
    start = seg["start"]; end = seg["end"]
    dur = end - start
    text = seg["text"].strip()
    if (dur <= max_len_sec and len(text) <= max_chars) or not words:
        return [seg]
    out: List[Dict[str, Any]] = []
    current_words: List[Dict[str, Any]] = []
    current_start = None
    def flush():
        nonlocal current_words, current_start
        if not current_words:
            return
        cs = current_start
        ce = current_words[-1]["end"]
        txt = " ".join(w["word"] for w in current_words).strip()
        out.append({"start": cs, "end": ce, "text": txt})
        current_words = []; current_start = None
    for w in words:
        if current_start is None:
            current_start = w["start"]
        next_len = len(" ".join([wd["word"] for wd in current_words] + [w["word"]]).strip())
        if ((w["end"] - current_start) > subseg_max_sec) or (next_len > max_chars):
            flush()
            current_start = w["start"]
        current_words.append(w)
    flush()
    final_out: List[Dict[str, Any]] = []
    for piece in out:
        pdur = piece["end"] - piece["start"]
        if pdur <= max_len_sec:
            final_out.append(piece); continue
        parts = max(2, int(math.ceil(pdur / max_len_sec)))
        words_piece = piece["text"].split()
        per = max(1, int(math.ceil(len(words_piece) / parts)))
        wi = 0; chunk_dur = pdur / parts
        for i in range(parts):
            cs = piece["start"] + i * chunk_dur
            ce = piece["start"] + (i + 1) * chunk_dur
            wchunk = words_piece[wi: wi + per]; wi += per
            final_out.append({"start": cs, "end": ce, "text": " ".join(wchunk).strip()})
    return final_out

def _split_long_segments(segs: List[Dict[str, Any]], words_map: Dict[int, List[Dict[str, Any]]],
                         max_len_sec: float, max_chars: int, subseg_max_sec: float) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for idx, s in enumerate(segs):
        start = float(s["start"]); end = float(s["end"])
        dur = end - start
        text = s["text"].strip()
        if dur <= max_len_sec and len(text) <= max_chars:
            out.append(s); continue
        wlist = words_map.get(idx, [])
        if wlist:
            out.extend(_split_segment_by_words(s, max_len_sec, wlist, max_chars, subseg_max_sec))
        else:
            words = text.split()
            if not words:
                continue
            pieces = max(2, int(math.ceil(len(text) / max_chars)))
            chunk_dur = dur / pieces
            per = max(1, int(math.ceil(len(words) / pieces)))
            wi = 0
            for i in range(pieces):
                cs = start + i * chunk_dur
                ce = start + (i + 1) * chunk_dur
                wchunk = words[wi: wi + per]; wi += per
                out.append({"start": cs, "end": ce, "text": " ".join(wchunk).strip()})
    return out

def _drop_leading_disclaimer(segs: List[Dict[str, Any]], max_at_sec: float = 4.0) -> List[Dict[str, Any]]:
    while segs and float(segs[0].get("start", 0.0)) <= max_at_sec and _looks_like_disclaimer(segs[0].get("text", "")):
        segs = segs[1:]
    cleaned: List[Dict[str, Any]] = []
    for s in segs:
        if float(s.get("start", 0.0)) <= max_at_sec and _looks_like_disclaimer(s.get("text", "")):
            continue
        cleaned.append(s)
    return cleaned

def _filter_noise_segments(segs: List[Dict[str, Any]], enabled: bool) -> List[Dict[str, Any]]:
    if not enabled:
        return segs
    return [s for s in segs if not _is_noise_segment(s.get("text", ""))]

# ---------------- LID (fastText) ----------------

class _LID:
    def __init__(self, path: str):
        self.ok = False
        self.model = None
        if not fasttext or not path or not os.path.isfile(path):
            print("[ytcms] LID disabled (fastText not available or model path missing)")
            return
        try:
            self.model = fasttext.load_model(path)
            self.ok = True
            print(f"[ytcms] LID loaded model={path}")
        except Exception as e:
            print(f"[ytcms] LID load failed: {e}")
            self.ok = False

    def predict(self, text: str) -> Tuple[str, float]:
        if not self.ok or not self.model:
            return ("unknown", 0.0)
        try:
            # FastText expects clean text
            t = (text or "").strip()
            if not t:
                return ("unknown", 0.0)
            labels, scores = self.model.predict(t, k=1)
            if not labels or not scores:
                return ("unknown", 0.0)
            lab = labels[0]  # '__label__fr'
            lang = lab.replace("__label__", "")
            score = float(scores[0])
            return (lang, score)
        except Exception:
            return ("unknown", 0.0)

# ---------------------------------------------------

class FasterWhisperProvider:
    def __init__(self, model_name: str, device: str, compute_type: str) -> None:
        compute_type = _sanitize_compute_type(compute_type)
        self.model_name = model_name
        self.device = device
        self.compute_type = compute_type
        self._model = WhisperModel(model_name, device=device, compute_type=compute_type)

        # Optional LID
        settings = get_settings()
        self._lid_conf = {
            "enabled": bool(getattr(settings, "lid_enabled", False)),
            "path": getattr(settings, "lid_model_path", "") or "",
            "confidence": float(getattr(settings, "lid_confidence", 0.70) or 0.70),
            "favor_neighbors": bool(getattr(settings, "lid_favor_neighbors", True)),
        }
        self._lid = _LID(self._lid_conf["path"]) if self._lid_conf["enabled"] else _LID("")  # disabled if no path

        try:
            size_label = getattr(self._model, "model_size", "unknown")
        except Exception:
            size_label = "unknown"
        print(f"[ytcms] Model loaded name={model_name} size_label={size_label} device={device} compute_type={compute_type}")

    # -------- core transcribe call wrapper --------
    def _transcribe_call(
        self,
        audio_path: str,
        lang: Optional[str],
        task: str,
        settings,
        force_cond_prev: Optional[bool] = None,
        force_initial_prompt: Optional[str] = None,
        want_words: bool = False,
    ):
        suppress_blank = bool(getattr(settings, "suppress_blank", False))
        initial_prompt_cfg = getattr(settings, "initial_prompt", "") or ""
        iprompt = (force_initial_prompt if force_initial_prompt is not None else initial_prompt_cfg)
        kwargs: Dict[str, Any] = dict(
            language=None if (lang == "auto" or lang is None) else lang,
            task=task,
            beam_size=settings.beam_size,
            vad_filter=settings.vad_filter,
            temperature=settings.temperature,
            compression_ratio_threshold=settings.compression_ratio_threshold,
            log_prob_threshold=settings.log_prob_threshold,
            no_speech_threshold=settings.no_speech_threshold,
            patience=settings.patience,
            condition_on_previous_text=(settings.condition_on_previous_text if force_cond_prev is None else force_cond_prev),
        )
        if suppress_blank:
            kwargs["suppress_blank"] = True
        if iprompt:
            kwargs["initial_prompt"] = iprompt
        if want_words:
            kwargs["word_timestamps"] = True
        try:
            return self._model.transcribe(audio_path, **kwargs)
        except TypeError:
            safe_keys = {
                "language","task","beam_size","vad_filter","temperature",
                "compression_ratio_threshold","log_prob_threshold","no_speech_threshold",
                "patience","condition_on_previous_text"
            }
            safe = {k: v for k, v in kwargs.items() if k in safe_keys}
            return self._model.transcribe(audio_path, **safe)

    def _collect_words(self, seg_obj, real_start: float) -> List[Dict[str, Any]]:
        words_out: List[Dict[str, Any]] = []
        for w in getattr(seg_obj, "words", []) or []:
            wtxt = getattr(w, "word", None)
            if not wtxt and isinstance(w, dict):
                wtxt = w.get("word")
            if not wtxt:
                continue
            wstart = getattr(w, "start", None)
            if wstart is None and isinstance(w, dict):
                wstart = w.get("start")
            wend = getattr(w, "end", None)
            if wend is None and isinstance(w, dict):
                wend = w.get("end")
            if wstart is None or wend is None:
                continue
            words_out.append({
                "word": str(wtxt).strip(),
                "start": float(wstart) + real_start,
                "end": float(wend) + real_start,
            })
        return words_out

    def _retry_edge_if_needed(self, chunk_data: List[Dict[str, Any]]) -> None:
        n = len(chunk_data)
        if n < 2:
            return
        lcur = chunk_data[0]["lang"]; lnxt = chunk_data[1]["lang"]
        if (lcur != lnxt and lnxt != "unknown") and (len(chunk_data[0]["segs"]) == 0 or lcur == "unknown"):
            chunk_data[0]["_force_lang"] = lnxt
        lprev = chunk_data[-2]["lang"]; lcur = chunk_data[-1]["lang"]
        if (lcur != lprev and lprev != "unknown") and (len(chunk_data[-1]["segs"]) == 0 or lcur == "unknown"):
            chunk_data[-1]["_force_lang"] = lprev

    # -------- mixed mode --------
    def _transcribe_mixed(
        self,
        media_path: str,
        task: str,
        progress_cb: Optional[Callable[[float], None]],
        settings,
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        total_dur = _ffprobe_duration_sec(media_path)
        mixed_retry_isolated_lang = bool(getattr(settings, "mixed_retry_isolated_lang", True))
        mixed_chunk_sec = int(getattr(settings, "mixed_chunk_sec", 30))
        mixed_overlap_sec = int(getattr(settings, "mixed_overlap_sec", 0))
        lookbehind_sec = float(getattr(settings, "mixed_lookbehind_sec", 1.0))
        max_segment_sec = float(getattr(settings, "max_segment_sec", 10.0))
        max_segment_chars = int(getattr(settings, "max_segment_chars", 140))
        subseg_max_chars = int(getattr(settings, "subseg_max_chars", 70))
        subseg_max_sec = float(getattr(settings, "subseg_max_sec", 6.0))
        disclaimer_max_sec = float(getattr(settings, "disclaimer_max_sec", 4.0))
        filter_noise = bool(getattr(settings, "filter_noise_segments", True))

        lid_enabled = self._lid_conf["enabled"] and self._lid.ok
        lid_conf = float(self._lid_conf["confidence"])
        favor_neighbors = bool(self._lid_conf["favor_neighbors"])

        if total_dur <= 0:
            seg_iter, info = self._transcribe_call(
                audio_path=media_path,
                lang="auto",
                task=task,
                settings=settings,
                want_words=True,
            )
            segs: List[Dict[str, Any]] = []
            words_map: Dict[int, List[Dict[str, Any]]] = {}
            for idx, seg in enumerate(seg_iter):
                segs.append({"start": float(seg.start), "end": float(seg.end), "text": seg.text.strip()})
                wlist = self._collect_words(seg, 0.0)
                if wlist:
                    words_map[idx] = wlist
            segs = _drop_leading_disclaimer(segs, disclaimer_max_sec)
            segs = _filter_noise_segments(segs, filter_noise)
            segs = _split_long_segments(segs, words_map, max_segment_sec, max_segment_chars, subseg_max_sec)
            meta = {
                "model": self.model_name,
                "device": self.device,
                "compute_type": self.compute_type,
                "segments": len(segs),
                "duration_sec": float(getattr(info, "duration", 0.0) or 0.0),
                "lang_requested": "mixed",
                "lang_detected": getattr(info, "language", None) or "unknown",
                "task": task,
                "mixed_mode": True,
            }
            return segs, meta

        chunk = max(5, mixed_chunk_sec)
        overlap = max(0, mixed_overlap_sec)
        if overlap >= chunk:
            overlap = 0

        print(f"[ytcms] Mixed mode enabled chunk={chunk}s overlap={overlap}s lookbehind={lookbehind_sec}s total_dur={total_dur:.3f}")

        tmp_dir = tempfile.mkdtemp(prefix="ytcms_mixed_")
        chunk_data: List[Dict[str, Any]] = []

        try:
            starts: List[float] = []
            s = 0.0
            step = (chunk - overlap) if chunk > overlap else chunk
            while s < total_dur:
                starts.append(s); s += step
            total_chunks = len(starts)

            prev_lang_for_heur = "unknown"

            for idx, start_sec in enumerate(starts, start=1):
                left = start_sec
                remaining = max(0.0, total_dur - left)
                dur = min(float(chunk), remaining) if remaining > 0 else float(chunk)
                out_wav = os.path.join(tmp_dir, f"chunk_{idx:04d}.wav")
                ok, real_start = _ffmpeg_extract_wav_chunk(media_path, left, dur, out_wav, lookbehind=lookbehind_sec)
                if not ok:
                    print(f"[ytcms] Mixed: chunk extract failed idx={idx} start={left:.3f} dur={dur:.3f}")
                    chunk_data.append({"start": left, "dur": dur, "lang": "unknown", "segs": [], "words_map": {}, "wav": out_wav, "real_start": real_start})
                    continue

                seg_iter, info = self._transcribe_call(
                    audio_path=out_wav,
                    lang=None,
                    task=task,
                    settings=settings,
                    force_cond_prev=False,
                    want_words=True,
                )
                raw_lang = getattr(info, "language", None) or "unknown"

                seg_list: List[Dict[str, Any]] = []
                words_map_local: Dict[int, List[Dict[str, Any]]] = {}
                for sidx, seg in enumerate(seg_iter):
                    seg_abs_start = float(seg.start) + real_start
                    seg_abs_end = float(seg.end) + real_start
                    seg_list.append({"start": seg_abs_start, "end": seg_abs_end, "text": seg.text.strip()})
                    wlist = self._collect_words(seg, real_start)
                    if wlist:
                        words_map_local[sidx] = wlist

                full_text = " ".join(s["text"] for s in seg_list)

                # LID correction pass
                lid_lang, lid_score = ("unknown", 0.0)
                if lid_enabled:
                    lid_lang, lid_score = self._lid.predict(full_text)
                    print(f"[ytcms] Mixed: LID chunk {idx}/{total_chunks} lid_lang={lid_lang} score={lid_score:.2f} whisper_lang={raw_lang}")

                corrected = _should_correct_lang(raw_lang, prev_lang_for_heur, full_text)
                lang_final = corrected or raw_lang

                # If LID is confident and differs from whisper -> prefer LID
                if lid_enabled and lid_lang not in ("unknown", "") and lid_score >= lid_conf and lid_lang != raw_lang:
                    lang_final = lid_lang
                    print(f"[ytcms] Mixed: LID override chunk {idx}/{total_chunks} raw={raw_lang} -> lid={lid_lang} ({lid_score:.2f})")

                # Favor neighbors: if neighbors agree and LID supports neighbor language moderately
                if favor_neighbors and 1 < idx < total_chunks:
                    prev_lang = chunk_data[idx - 2]["lang"] if idx >= 2 else "unknown"
                    next_lang = "unknown"  # not yet known at this point; apply neighbor favor in second pass

                if lang_final not in ("unknown", ""):
                    prev_lang_for_heur = lang_final

                chunk_data.append({
                    "start": left, "dur": dur, "lang": lang_final,
                    "segs": seg_list, "words_map": words_map_local,
                    "wav": out_wav, "real_start": real_start,
                    "lid_lang": lid_lang, "lid_score": lid_score,
                })

                print(f"[ytcms] Mixed: chunk {idx}/{total_chunks} start={left:.2f}s dur={dur:.2f}s lang={lang_final} segs={len(seg_list)}")
                if progress_cb:
                    frac = min(max(idx / total_chunks, 0.0), 1.0)
                    p = 0.05 + 0.85 * frac; p = min(p, 0.9)
                    print(f"[ytcms] Progress mixed {idx}/{total_chunks} p={_fmt_pct(p)}")
                    _safe_progress(progress_cb, p)

            # Second pass: favor neighbors using LID
            if favor_neighbors and total_chunks >= 3 and lid_enabled:
                for i in range(1, total_chunks - 1):
                    lprev = chunk_data[i - 1]["lang"]
                    lcur = chunk_data[i]["lang"]
                    lnext = chunk_data[i + 1]["lang"]
                    lid_lang = chunk_data[i]["lid_lang"]; lid_score = chunk_data[i]["lid_score"]
                    # If neighbors agree and current differs, and LID supports neighbor moderately
                    if lprev == lnext and lprev != "unknown" and lcur != lprev:
                        if lid_lang == lprev and lid_score >= (lid_conf * 0.8):
                            chunk_data[i]["_force_lang"] = lprev
                            print(f"[ytcms] Mixed: neighbor-favor set for chunk {i+1}/{total_chunks} lang={lprev} lid_score={lid_score:.2f}")

            # Retry isolated + edges + neighbor-favor
            if mixed_retry_isolated_lang and total_chunks >= 2:
                if total_chunks >= 3:
                    for i in range(1, total_chunks - 1):
                        lprev = chunk_data[i - 1]["lang"]
                        lcur = chunk_data[i]["lang"]
                        lnext = chunk_data[i + 1]["lang"]
                        need_retry = False; forced_lang = chunk_data[i].get("_force_lang")
                        if forced_lang:
                            need_retry = True
                        if not need_retry and len(chunk_data[i]["segs"]) == 0:
                            need_retry = True
                            forced_lang = lprev if lprev == lnext and lprev != "unknown" else (lprev if lprev != "unknown" else (lnext if lnext != "unknown" else None))
                        if not need_retry and (lprev == lnext and lprev != "unknown" and lcur != lprev):
                            need_retry = True; forced_lang = lprev
                        if not need_retry and lcur in ("zh","ko","ja","es"):
                            text_all = " ".join(s["text"] for s in chunk_data[i]["segs"])
                            stats = _analyze_chars(text_all)
                            if lcur in ("zh","ko","ja") and stats["cjk"] == 0 and lprev == lnext and lprev != "unknown":
                                need_retry = True; forced_lang = lprev
                            elif lcur == "es" and stats["accent_ratio"] > 0.03 and stats["accents"] >= 5:
                                need_retry = True; forced_lang = "fr"
                        if need_retry and forced_lang:
                            wav = chunk_data[i]["wav"]; real_start = chunk_data[i]["real_start"]
                            try:
                                seg_iter2, info2 = self._transcribe_call(
                                    audio_path=wav, lang=forced_lang, task=task,
                                    settings=settings, force_cond_prev=False, want_words=True
                                )
                                seg_list2: List[Dict[str, Any]] = []; words_map_local2: Dict[int, List[Dict[str, Any]]] = {}
                                for sidx2, seg2 in enumerate(seg_iter2):
                                    ss2 = float(seg2.start) + real_start; ee2 = float(seg2.end) + real_start
                                    seg_list2.append({"start": ss2, "end": ee2, "text": seg2.text.strip()})
                                    wlist2 = self._collect_words(seg2, real_start)
                                    if wlist2:
                                        words_map_local2[sidx2] = wlist2
                                chunk_data[i]["segs"] = seg_list2
                                chunk_data[i]["words_map"] = words_map_local2
                                chunk_data[i]["lang"] = forced_lang
                                print(f"[ytcms] Mixed: retry chunk {i+1}/{total_chunks} forced_lang={forced_lang} segs={len(seg_list2)}")
                            except Exception as re:
                                print(f"[ytcms] Mixed: retry failed idx={i+1} err={re}")

                self._retry_edge_if_needed(chunk_data)
                for i, cd in enumerate(chunk_data):
                    forced_lang = cd.get("_force_lang")
                    if not forced_lang:
                        continue
                    wav = cd["wav"]; real_start = cd["real_start"]
                    try:
                        seg_iter3, info3 = self._transcribe_call(
                            audio_path=wav, lang=forced_lang, task=task,
                            settings=settings, force_cond_prev=False, want_words=True
                        )
                        segs3: List[Dict[str, Any]] = []; words_map_local3: Dict[int, List[Dict[str, Any]]] = {}
                        for sidx3, seg3 in enumerate(seg_iter3):
                            ss3 = float(seg3.start) + real_start; ee3 = float(seg3.end) + real_start
                            segs3.append({"start": ss3, "end": ee3, "text": seg3.text.strip()})
                            wlist3 = self._collect_words(seg3, real_start)
                            if wlist3:
                                words_map_local3[sidx3] = wlist3
                        cd["segs"] = segs3; cd["words_map"] = words_map_local3; cd["lang"] = forced_lang
                        print(f"[ytcms] Mixed: edge-retry chunk {i+1}/{total_chunks} forced_lang={forced_lang} segs={len(segs3)}")
                    except Exception as re:
                        print(f"[ytcms] Mixed: edge-retry failed idx={i+1} err={re}")

            # Aggregate + post-processing
            all_segs: List[Dict[str, Any]] = []
            words_map_global: Dict[int, List[Dict[str, Any]]] = {}
            seg_global_idx = 0
            lid_summary: List[Dict[str, Any]] = []
            for cd in chunk_data:
                lid_summary.append({"lang": cd.get("lid_lang", "unknown"), "score": cd.get("lid_score", 0.0)})
                for local_idx, sdict in enumerate(cd["segs"]):
                    all_segs.append(sdict)
                    local_words = cd.get("words_map", {}).get(local_idx)
                    if local_words:
                        words_map_global[seg_global_idx] = local_words
                    seg_global_idx += 1

            disclaimer_max_sec = float(getattr(settings, "disclaimer_max_sec", 4.0))
            filter_noise = bool(getattr(settings, "filter_noise_segments", True))
            all_segs = _drop_leading_disclaimer(all_segs, disclaimer_max_sec)
            all_segs = _filter_noise_segments(all_segs, filter_noise)
            all_segs = _split_long_segments(all_segs, words_map_global, max_segment_sec, max_segment_chars, subseg_max_sec)
            all_segs = _drop_leading_disclaimer(all_segs, disclaimer_max_sec)
            all_segs = _filter_noise_segments(all_segs, filter_noise)

            meta = {
                "model": self.model_name,
                "device": self.device,
                "compute_type": self.compute_type,
                "segments": len(all_segs),
                "duration_sec": total_dur,
                "lang_requested": "mixed",
                "lang_detected": "mixed",
                "task": task,
                "mixed_mode": True,
                "mixed_chunk_sec": mixed_chunk_sec,
                "mixed_overlap_sec": overlap,
                "mixed_retry_isolated_lang": mixed_retry_isolated_lang,
                "mixed_lookbehind_sec": lookbehind_sec,
                "mixed_chunk_langs": [cd["lang"] for cd in chunk_data],
                "mixed_chunk_lid": lid_summary,
            }
            print(f"[ytcms] Mixed: done chunks={total_chunks} total_segs={len(all_segs)}")
            return all_segs, meta
        finally:
            try:
                for fn in os.listdir(tmp_dir):
                    try:
                        os.remove(os.path.join(tmp_dir, fn))
                    except Exception:
                        pass
                os.rmdir(tmp_dir)
            except Exception:
                pass

    # -------- single pass mode --------
    async def transcribe(
        self,
        video_path: str,
        lang: str,
        task: str,
        progress_cb: Optional[Callable[[float], None]] = None,
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        settings = get_settings()
        if task not in ("transcribe", "translate"):
            task = "transcribe"

        def _run():
            if progress_cb:
                _safe_progress(progress_cb, 0.05)
            print(f"[ytcms] Transcribe start file={video_path} lang_req={lang} task={task} beam={settings.beam_size} vad={settings.vad_filter} cond_prev={settings.condition_on_previous_text}")

            if (lang or "").lower().strip() == "mixed":
                segs, meta = self._transcribe_mixed(video_path, task, progress_cb, settings)
                if progress_cb: _safe_progress(progress_cb, 0.9)
                return segs, meta

            seg_iter, info = self._transcribe_call(
                audio_path=video_path,
                lang=lang,
                task=task,
                settings=settings,
                want_words=True,
            )
            duration = float(getattr(info, "duration", 0.0) or 0.0)
            print(f"[ytcms] Transcribe info duration={duration:.3f} lang_detected={getattr(info,'language',None)}")

            raw_segs: List[Dict[str, Any]] = []
            words_map: Dict[int, List[Dict[str, Any]]] = {}
            for idx, seg in enumerate(seg_iter):
                raw_segs.append({"start": float(seg.start), "end": float(seg.end), "text": seg.text.strip()})
                wlist = self._collect_words(seg, 0.0)
                if wlist:
                    words_map[idx] = wlist
                if len(raw_segs) <= 3 or len(raw_segs) % 25 == 0:
                    print(f"[ytcms] seg#{len(raw_segs)} {seg.start:.2f}->{seg.end:.2f} text='{seg.text[:80].strip()}'")
                if progress_cb:
                    if duration > 0:
                        frac = min(max(float(seg.end) / duration, 0.0), 1.0)
                        p = 0.05 + 0.85 * frac
                    else:
                        assumed = float(getattr(settings, "progress_assumed_max_segs", 20) or 20)
                        p = 0.05 + 0.85 * (len(raw_segs) / assumed)
                    p = min(p, 0.9)
                    print(f"[ytcms] Progress p={_fmt_pct(p)}")
                    _safe_progress(progress_cb, p)

            if progress_cb:
                _safe_progress(progress_cb, 0.9)

            max_segment_sec = float(getattr(settings, "max_segment_sec", 10.0))
            max_segment_chars = int(getattr(settings, "max_segment_chars", 140))
            subseg_max_chars = int(getattr(settings, "subseg_max_chars", 70))
            subseg_max_sec = float(getattr(settings, "subseg_max_sec", 6.0))
            disclaimer_max_sec = float(getattr(settings, "disclaimer_max_sec", 4.0))
            filter_noise = bool(getattr(settings, "filter_noise_segments", True))

            raw_segs = _drop_leading_disclaimer(raw_segs, disclaimer_max_sec)
            raw_segs = _filter_noise_segments(raw_segs, filter_noise)
            raw_segs = _split_long_segments(raw_segs, words_map, max_segment_sec, max_segment_chars, subseg_max_sec)
            raw_segs = _drop_leading_disclaimer(raw_segs, disclaimer_max_sec)
            raw_segs = _filter_noise_segments(raw_segs, filter_noise)

            meta = {
                "model": self.model_name,
                "device": self.device,
                "compute_type": self.compute_type,
                "segments": len(raw_segs),
                "duration_sec": duration,
                "lang_requested": lang,
                "lang_detected": getattr(info, "language", None),
                "task": task,
                "mixed_mode": False,
            }
            print(f"[ytcms] Transcribe done segments={len(raw_segs)} lang_used={meta['lang_detected']}")
            return raw_segs, meta

        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, _run)

_provider_singleton: FasterWhisperProvider | None = None

def get_provider(model: str, device: str, compute_type: str) -> FasterWhisperProvider:
    global _provider_singleton
    if _provider_singleton is None:
        _provider_singleton = FasterWhisperProvider(model, device, compute_type)
    return _provider_singleton